# WEEK 1 ML ASSIGNMENTS

# GROUP MEMBERS 

### Rugved - 33273
### Onkar - 33268
### Shubham - 33265

## We all installed Anaconda and then we learnt how to use it and then carried on with the tasks in one notebook only.

In [1]:
import numpy as np

In [2]:
array1 = np.array([0,20,10,40,60,80])
array2 = np.array([10,30,40,50,70])

In [3]:
union = np.union1d(array1,array2)

In [4]:
print(union)

[ 0 10 20 30 40 50 60 70 80]


In [5]:
array1 = np.array([1,2])
array2 = np.array([4,5])
print(np.greater(array1,array2))
print(np.greater_equal(array1,array2))

[False False]
[False False]


In [6]:
print(np.less(array1,array2))
print(np.less_equal(array1,array2))

[ True  True]
[ True  True]


In [7]:
array = np.array(np.zeros((2,3)))
print(array)
print(array.shape)
print(type(array))

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
<class 'numpy.ndarray'>


In [8]:
array = np.array(np.zeros((3,5)))
np.fill_diagonal(array,12)

In [9]:
print(array)

[[12.  0.  0.  0.  0.]
 [ 0. 12.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]]


In [10]:
array = np.array([2,43,654,23,1,231])
array.sort(kind='quicksort')
print(array)

[  1   2  23  43 231 654]
